description paragraph added
barakadanny/Hello_Microverse pull request #3
Opened 2022-06-28 17:13 UTC by barakadanny

added a paragraph to describe the website

2022-06-28 19:29 UTC, youmari requested changes
Hi @barakadanny , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Implement the requirements

## Required Changes ♻️

- [x] please make sure to use the right linters files and delete the others and also make sure that they are passing 

- [ ] You should add a Descriptive branch name, title, and short summary that tells in detail what you've done in Pull Request
- [x]  It would be better if you add the test.md file to `.gitignore` file as required

- [ ] Please make sure next time to use the[ rules ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)of writing Desctiprive commit messages in order for your PR will be pro 


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 13:59 UTC, 1GORDON approved these changes
Hi @barakadanny, 

- You have done a great job implementing the required changes. ✅.
- ### **Project Approved ✅**

![Approved](https://user-images.githubusercontent.com/61562626/133470391-bf4e9793-9886-4b0d-b12c-185d58ad39de.gif)


Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉 


 ## Optional Changes
_Please check the inline comments below._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 13:59 UTC, 1GORDON commented on index.html
>      </div>
Hello @barakadanny. 
- [x] [Optional] You may try to stick to the text provided in the project requirements. "Hello Microverse!"

2022-06-29 13:59 UTC, 1GORDON commented on .gitignore
> +test.md
Great job so far @barakadanny.

- [x] [Optional] The .gitignore file should include both the node_modules and the test.md file.

2022-06-29 14:17 UTC, barakadanny commented on .gitignore
> +test.md
I will take care of that

2022-06-29 14:18 UTC, barakadanny commented on index.html
>      </div>
alright.

2022-06-30 10:28 UTC, merged